title: Dr. Matthias Minihold - Applied Cryptographer
description: ~ Mathematics, Cryptology, and IT Security Enthusiast ~
url: https://MatthiasMi.github.io/
author: Dr. Matthias Minihold
lang: english

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
