author: Dr. Matthias Minihold
description: ~ Mathematics, Cryptology, and IT Security Enthusiast ~
title: Dr. Matthias Minihold -- Applied Cryptographer
lang: english

url: https://MatthiasMi.github.io
baseurl: ''

theme: jekyll-theme-midnight
